name: Deploy to Self-Hosted Server

on:
  workflow_run:
    workflows: ["Deploy Production Environment"]
    types:
      - completed

jobs:
  deploy:
    runs-on: sh-05_gateway

    steps:
      - name: docker setup
        uses: docker/setup-docker-action@v4.3.0
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: docker pull
        uses: codebysandip/docker-pull-auto-action@v1.5
        with:
          # docker image. Example sandipj/react-ssr-doc
          docker-image: ${{ vars.DOCKER_IMAGE_NAME }}
          # docker tag which you just generated. Example latest
          docker-tag: latest
          # domain on which request will send
          domain: ${{ secrets.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}
      - name: Deploy with Docker run
        run: |
          docker stop ${{ vars.DOCKER_CONTAINER_NAME }} || true
          docker rm ${{ vars.DOCKER_CONTAINER_NAME }} || true
          docker run -d --name ${{ vars.DOCKER_CONTAINER_NAME }} -p 11080:80 ${{ vars.DOCKER_IMAGE_NAME }}:latest
        

          
