name: Deploy Production Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  publish:
    environment: production
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps: 
      - name: docker setup
        uses: docker/setup-docker-action@v4.3.0
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: checkout
        uses: actions/checkout@v4
      - name: list files
        run: ls -a
      - name: docker build
        run: docker build . --file ${{ vars.DOCKER_FILE }} --tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
      - name: docker push
        run: docker push ${{ vars.DOCKER_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}
        
