name: Deploy Production Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
      - name: docker setup
        uses: docker/setup-docker-action@v4.3.0
      - name: docker build
        run: docker build . --file ./Dockerfile --tag ${{vars.DOCKER_IMAGE_NAME}}:production
      - name: docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
      - name: docker rm old image
        run: docker rmi ${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{vars.DOCKER_IMAGE_NAME}}:production
      - name: docker push new image
        run: docker push ${{ secrets.DOCKER_REGISTRY_USERNAME }}/${{vars.DOCKER_IMAGE_NAME}}:production
        
