name: Deploy Development Environment
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
jobs:
  publish:
    environment: development
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Docker setup
        uses: docker/setup-docker-action@v4.3.0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_ID }}
          aws-region: us-east-1
      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker build
        run: |
          docker build . -t ${{ vars.DOCKER_IMAGE_NAME }}:dev
      - name: Docker tag
        run: docker tag ${{ vars.DOCKER_IMAGE_NAME }}:dev ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:dev
      - name: Docker push
        run: docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:dev

      - name: docker build
        run: |
          docker build . \
            --build-arg ConfigProvider__RepoOwner=${{ vars.ENV_REPO_OWNER }} \
            --build-arg ConfigProvider__RepoName=${{ vars.ENV_REPO_NAME }} \
            --build-arg ConfigProvider__Branch=${{ vars.ENV_BRANCH }} \
            --build-arg ConfigProvider__UserName=${{ secrets.ENV_USER_NAME }} \
            --build-arg ConfigProvider__Password=${{ secrets.ENV_PASSWORD }} \
            --build-arg ConfigProvider__AppId=${{ secrets.ENV_APP_ID }} \
            --build-arg ConfigProvider__AppSecret=${{ secrets.ENV_SECRET }} \
            --build-arg DOTNET_ENVIRONMENT=${{ vars.DOTNET_ENV }} \
            --file ${{ vars.DOCKER_FILE }} --tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.run_id }}

  deploy:
    needs: publish
    name: Deploy docker image
    environment: development
    runs-on: sh-06_dev
    steps:
      - name: Docker pull
        run: |
          sudo docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:dev
      - name: Deploy with docker run
        run: |
          sudo docker stop ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker rm ${{ vars.DOCKER_CONTAINER_NAME }} || true
          sudo docker run -d --name ${{ vars.DOCKER_CONTAINER_NAME }} \
            -p ${{ vars.DOCKER_CONTAINER_PORT }}:80 \
            -e ConfigProvider__RepoOwner=${{ vars.ENV_REPO_OWNER }} \
            -e ConfigProvider__RepoName=${{ vars.ENV_REPO_NAME }} \
            -e ConfigProvider__Branch=${{ vars.ENV_BRANCH }} \
            -e ConfigProvider__UserName=${{ secrets.ENV_USER_NAME }} \
            -e ConfigProvider__Password=${{ secrets.ENV_PASSWORD }} \
            -e ConfigProvider__AppId=${{ secrets.ENV_APP_ID }} \
            -e ConfigProvider__AppSecret=${{ secrets.ENV_SECRET }} \
            -e DOTNET_ENVIRONMENT=${{ vars.DOTNET_ENV }} \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_NAMESPACE }}/${{ vars.DOCKER_IMAGE_NAME }}:dev
